name: build

on:
  push:
    branches:
      - '**'

env:
  DOTNET_NOLOGO: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-java:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: build
        shell: pwsh
        run: ./tools/build-java.ps1

  test-dotnet:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      # fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest Doesn't work yet
          - windows-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: |
            8
            10
          dotnet-quality: ga

      - name: prepare
        run: dotnet restore

      - name: tfm
        # building net461 doesn't work on non windows
        if: matrix.os != 'windows-latest'
        run: echo "NoNet4=true" >> $GITHUB_ENV

      - name: build
        run: dotnet build --no-restore

      - name: test
        run: dotnet test --no-build

      - name: Codecov test results
        if: github.event_name != 'merge_group' && !cancelled()
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          report_type: test_results
          fail_ci_if_error: true

      - name: Codecov coverage results
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          files: '**/TestResults/*/*.cobertura.xml'
          fail_ci_if_error: true

  build:
    runs-on: windows-latest
    timeout-minutes: 15
    needs:
      - test-java
      - test-dotnet

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: 10
          dotnet-quality: ga

      - name: prepare
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore -c Release

      - name: pack
        run: dotnet pack --no-build -o bin -c Release

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: packages
          path: bin/*.nupkg

  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Important for changelog
          # doesn't work with git-cliff
          # https://github.com/orhun/git-cliff/issues/1521
          # filter: blob:none
          show-progress: false

      - name: Generate changelog with git-cliff
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          args: --unreleased --strip all
        env:
          # DEBUG: true
          OUTPUT: CHANGELOG.md

      - name: Adding changelog to summary
        run: cat CHANGELOG.md >> $GITHUB_STEP_SUMMARY
