name: release

on:
  push:
    tags:
      - v*

env:
  DOTNET_NOLOGO: true
  Configuration: Release

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: windows-latest
    timeout-minutes: 15
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: prepare
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore

      - name: pack
        run: dotnet pack --no-build -o bin

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: packages
          path: bin/*.nupkg

      - name: deploy github.com
        run: find bin -name '*.nupkg' | xargs dotnet nuget push -s $NUGET_SOURCE -k $NUGET_KEY --skip-duplicate --force-english-output
        shell: bash
        env:
          NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy nuget.org
        run: find bin -name '*.nupkg' | xargs dotnet nuget push -s $NUGET_SOURCE -k $NUGET_KEY --skip-duplicate --force-english-output
        shell: bash
        env:
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref_name, '-') }}
