name: release

on:
  push:
    tags:
      - v*

env:
  DOTNET_NOLOGO: true
  ProjectLoadStyle: All

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: windows-latest
    timeout-minutes: 15
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: actions/cache@c1a5de879eb890d062a85ee0252d6036480b1fe2 # v3.2.1
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: prepare
        shell: pwsh
        run: ./tools/prepare.ps1

      - name: build
        shell: pwsh
        run: ./tools/build.ps1

      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: packages
          path: bin/*.nupkg

      - name: deploy github.com
        run: |
          dotnet nuget add source --username $NUGET_USR --password $NUGET_PSW --store-password-in-clear-text --name github $NUGET_SOURCE
          find bin -name '*.nupkg' | xargs dotnet nuget push  -s github --skip-duplicate --force-english-output
        shell: bash
        env:
          NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          NUGET_USR: ${{ github.repository_owner }}
          NUGET_PSW: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy nuget.org
        run: find bin -name '*.nupkg' | xargs dotnet nuget push -s $NUGET_SOURCE -k $NUGET_KEY --skip-duplicate --force-english-output
        shell: bash
        env:
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

      - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref_name, '-') }}
