name: release

on:
  push:
    tags:
      - v*

env:
  DOTNET_NOLOGO: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: windows-latest
    timeout-minutes: 15
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/cache/restore@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: prepare
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore -c Release

      - name: pack
        run: dotnet pack --no-build -o bin -c Release

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: packages
          path: bin/*.nupkg

      - name: deploy github.com
        run: find bin -name '*.nupkg' | xargs dotnet nuget push -s $NUGET_SOURCE -k $NUGET_KEY --skip-duplicate --force-english-output
        shell: bash
        env:
          NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy nuget.org
        run: find bin -name '*.nupkg' | xargs dotnet nuget push -s $NUGET_SOURCE -k $NUGET_KEY --skip-duplicate --force-english-output
        shell: bash
        env:
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

  gh-release:
    needs:
      - release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0 # Important for changelog
          filter: blob:none
          show-progress: false

      - name: prepare version
        run: echo VERSION=${GITHUB_REF_NAME#v} >> $GITHUB_ENV # trim leading 'v' from tag name

      - name: Generate changelog with git-cliff
        uses: tj-actions/git-cliff@b8b856ab6829a813d4ed58476b6faaec9c2b24ef # v1.4.2
        with:
          args: --latest --strip all
          output: "CHANGELOG.md"

      - name: Create Release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          bodyFile: "CHANGELOG.md"
          name: ${{ env.VERSION }}
          prerelease: ${{ contains(github.ref_name, '-') }}
